"""Pydantic schemas for the entire pipeline."""

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel, Field


# ── API Request / Response ──────────────────────────────────────────


class AnalyzeRequest(BaseModel):
    """Incoming request payload."""

    ticker: str = Field(..., min_length=1, max_length=10, examples=["AAPL"])


# ── Financial Data ──────────────────────────────────────────────────


class PriceSnapshot(BaseModel):
    date: str
    open: float
    high: float
    low: float
    close: float
    volume: int


class KeyMetrics(BaseModel):
    market_cap: Optional[float] = None
    pe_ratio: Optional[float] = None
    forward_pe: Optional[float] = None
    peg_ratio: Optional[float] = None
    price_to_book: Optional[float] = None
    dividend_yield: Optional[float] = None
    beta: Optional[float] = None
    fifty_two_week_high: Optional[float] = None
    fifty_two_week_low: Optional[float] = None
    current_price: Optional[float] = None
    target_mean_price: Optional[float] = None
    earnings_growth: Optional[float] = None
    revenue_growth: Optional[float] = None
    profit_margins: Optional[float] = None
    operating_margins: Optional[float] = None
    return_on_equity: Optional[float] = None
    debt_to_equity: Optional[float] = None
    free_cash_flow: Optional[float] = None
    total_revenue: Optional[float] = None
    net_income: Optional[float] = None
    total_debt: Optional[float] = None
    total_cash: Optional[float] = None


class FinancialData(BaseModel):
    """Normalized stock data bundle passed to every agent."""

    ticker: str
    company_name: str
    sector: Optional[str] = None
    industry: Optional[str] = None
    description: Optional[str] = None
    metrics: KeyMetrics
    recent_prices: list[PriceSnapshot] = Field(default_factory=list)
    income_statement_highlights: dict = Field(default_factory=dict)
    balance_sheet_highlights: dict = Field(default_factory=dict)
    cash_flow_highlights: dict = Field(default_factory=dict)
    fetched_at: str = ""


# ── Agent Output ────────────────────────────────────────────────────


class AgentOutput(BaseModel):
    """Structured output produced by each analyst agent."""

    agent: str
    stance: str  # "bullish" | "bearish" | "neutral"
    thesis: str
    key_points: list[str]
    risks: list[str]
    opportunities: list[str] = Field(default_factory=list)
    data_references: list[str] = Field(
        default_factory=list,
        description="Specific data points from the input that support claims",
    )
    confidence: float = Field(
        ge=0.0, le=1.0, description="Confidence score 0-1"
    )


# ── Cross-Examination ──────────────────────────────────────────────


class CrossExamResult(BaseModel):
    """Result of one agent examining another's output."""

    reviewer: str
    target: str
    critiques: list[str]
    agreements: list[str] = Field(default_factory=list)
    bias_flags: list[str] = Field(default_factory=list)
    missing_considerations: list[str] = Field(default_factory=list)
    severity: str = Field(
        default="medium",
        description="low | medium | high — overall severity of issues found",
    )


# ── Final Report ────────────────────────────────────────────────────


class FinalReport(BaseModel):
    """Complete output returned by the moderator."""

    ticker: str
    company_name: str
    analysis_date: str
    executive_summary: str
    bull_case: AgentOutput
    bear_case: AgentOutput
    neutral_case: AgentOutput
    cross_examination_results: list[CrossExamResult] = Field(
        default_factory=list
    )
    moderator_commentary: str
    key_catalysts: list[str] = Field(default_factory=list)
    primary_risks: list[str] = Field(default_factory=list)
    disclaimer: str = (
        "This analysis is AI-generated for informational purposes only. "
        "It provides objective analysis and statements but does not provide "
        "investment advice or recommendations."
    )


# ── Live Debate ─────────────────────────────────────────────────────


class DebateMessage(BaseModel):
    """Output generated by an agent during a live debate round."""

    speaker: str
    message: str
    references: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=100.0)


# ── Error ───────────────────────────────────────────────────────────


class ErrorResponse(BaseModel):
    detail: str
    error_code: str = "INTERNAL_ERROR"
